# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Injin Kim
title: A new Back-end Web Developer
email: injin333@uos.ac.kr
website: www.github.com/somizoo

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: somizoo
linkedin_username: Injin Kim

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be

# About Section
# about_title: About Me
about_profile_image: images/injin.jpg
about_content: | # this will include new lines to allow paragraphs
  **On my way, My way trip**


  한명의 새로운 개발자로써의 여행을 떠나고 싶은 <mark>김인진</mark> 이라고 합니다!
  
  20살 이후로 제가 해야 하는 일에 누구보다 최선을 다하였으며, 결과로 증명하였습니다.
  
  앞으로의 개발자로써의 길 또한 누구보다 열심히 달릴 자신이 있습니다.
  
  저의 부족함을 채울 수 있는 열정과 성실성, 그리고 저의 가능성을 봐주셨으면 좋겠습니다.
  

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Us Way Trip
        link: github.com/somizoo/project
        # link_text: Project Website
        additional_links:
          - title: sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        [네이버 주소](<https://www.naver.com, "네이버 블로그")
         
        quote: >
          국비 과정에서 진행했던 프로젝트 입니다.
          
        description: | # this will include new lines to allow paragraphs
          프로젝트에서 가장 중요한 것은 <mark>팀워크</mark>라고 생각합니다. 저의 부족함을 채울 수 있는 팀원이 있고, 저의 역량으로 수행할 수 있는 역할이 있다고 생각합니다.
          
          개발은 협업입니다. 혼자 할 수 없다고 생각합니다. 개발자에게 있어 코딩 실력보다 중요한 것은 좋은 <mark>팀워크</mark>를 만들어 나가기 위한 노력이 아닐까 싶습니다.
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: HanaTI
        link: hanati.co.kr
        # link_text: boringcompany.com
        sub_title: Junior Core Banking Developer
        caption: November 2020 - Present
        quote: >
          Core Banking Developer
        description: | # this will include new lines to allow paragraphs
            After 6 months of Trainning(Apr - Oct 2020), worked as full-time Core Banking Developer covering Common, Customer, AML, Factoriy modules.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Hankuk University of Foreign Studies
        caption: 2010 - 2016
        sub_title: BSc Thai Language
        quote: >
          Hankuk University of Foreing Studies, aka HUFS, is best Foreign-study education institution in South Korea.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          In HUFS, I had various chances to get along with students from abroad, so it helped me to be a multicultural individual who can get easy with exotic cultures.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Collecting Keyboards (Especially Capactive keyboards)
      - Gaming
      - Pilates
      - Beer


# Footer
footer_show_references: true
# references_title: Nice to meet you (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
